services:
  - type: web
    name: social-monitor-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: BOT_TOKEN
        value: 8324581466:AAEJ87WR-a7_82pNpX5VxWgBt64N2vV3msU
      - key: INSTAGRAM_TARGET
        value: nasyy.k
      - key: TIKTOK_TARGET
        value: naasyyk
      - key: INSTAGRAM_SESSION_ID
        value: 77589621865%3A4j0m93Nh3uxSCD%3A28%3AAYkrApYfsWnYWSS8OCeuPyE3E3RdJK6XScxvsT4fOw
      - key: CHECK_INTERVAL_SECONDS
        value: "1800"
